build fix, unsermon needs LIBEV_CFLAGS (broken since 9ca3d36b)
In file included from mcast.c:67:0:
unserding-private.h:61:17: fatal error: ev.h: No such file or directory